name: Format

on:
  push:
  pull_request:
    branches: [main]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5

      - run: npm install prettier prettier-plugin-toml

      - run: npx prettier --check .

  rustfmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install rustfmt
        run: |
          rustup update --no-self-update
          rustup component add cargo rustfmt

      - name: Run rustfmt
        run: cargo fmt --check
