name: Format

on:
  push:
  pull_request:
    branches: [main]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4

      - run: npm install prettier

      - run: npx prettier --check .

  isort:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v3

      - name: Set up Python
        run: uv python install

      - name: Run isort
        run: uv run isort --check-only --diff .

  black:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v3

      - run: uv python install

      - name: Run black
        run: uv run black --check --diff .
