name: Lint

on:
  push:
  pull_request:
    branches: [main]

jobs:
  clippy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install clippy
        run: |
          rustup update --no-self-update
          rustup component add cargo clippy

      - name: Run clippy
        run: cargo clippy -- -D warnings
